### PR TITLE
Fix for InvalidOperationException in Blazor authz

### LINKED ISSUE #3964: InvalidOperationException in Blazor 8 state manager
The application context manager for Blazor server, in Blazor 8, is unable to get the user identity from the `AuthenticationStateProvider` service, because Blazor 8 no longer allows this type to be accessed outside the context of a razor component.

My research indicates that we should try to access the HttpContext _first_ and if that isn't available, then we should fall back to the `AuthenticationStateProvider` to get the current user identity.

This affects CSLA 8 and 9.

### PR DESCRIPTION
**Pull request by rockfordlhotka**
Closes #3964

#3965

### CODE REVIEW

File: Source/Csla.AspNetCore/Blazor/ApplicationContextManagerBlazor.cs [hunk 1]
```diff
@@ -65,40 +65,29 @@ public ApplicationContextManagerBlazor(IHttpContextAccessor hca, AuthenticationS
...
         Task<AuthenticationState> task;
         try
         {
           task = AuthenticationStateProvider.GetAuthenticationStateAsync();
           await task;
         }
-        catch (InvalidOperationException ex)
+        catch (InvalidOperationException)
         {
           task = Task.FromResult(new AuthenticationState(UnauthenticatedPrincipal));
```
Comment (StefanOssendorf) [inline Source/Csla.AspNetCore/Blazor/ApplicationContextManagerBlazor.cs:87]: Isn't the `SetHostPrinciapl(task)` now missing in this case and we end up with no user?

File: Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs [hunk 2]
```diff
@@ -40,14 +41,18 @@ public class ApplicationContextManagerInMemory : IContextManager, IDisposable
...
     /// Creates an instance of the object, initializing it
     /// with the required IServiceProvider.
     /// </summary>
+    /// <param name="httpContextAccessor"></param>
     /// <param name="authenticationStateProvider">AuthenticationStateProvider service</param>
     /// <param name="activeCircuitState"></param>
-    public ApplicationContextManagerInMemory(AuthenticationStateProvider authenticationStateProvider, ActiveCircuitState activeCircuitState)
+    public ApplicationContextManagerInMemory(IHttpContextAccessor httpContextAccessor, AuthenticationStateProvider authenticationStateProvider, ActiveCircuitState activeCircuitState)
     {
+      HttpContext = httpContextAccessor.HttpContext;
```
Comment (StefanOssendorf) [inline Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs:55]: Is `IHttpContextAccessor` _always_ registered within the DI? Even in a real Blazor WASM scenario? That looks dangerous.

File: Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs [hunk 3]
```diff
@@ -57,29 +62,30 @@ public ApplicationContextManagerInMemory(AuthenticationStateProvider authenticat
...
         {
-          SetHostPrincipal(task);
+          task = AuthenticationStateProvider.GetAuthenticationStateAsync();
+          await task;
         }
-        else
+        catch (InvalidOperationException)
         {
-          throw;
+          task = Task.FromResult(new AuthenticationState(UnauthenticatedPrincipal));
```
Comment (StefanOssendorf) [inline Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs:85]: `SetHostPrincipal` not necessary anymore?

File: Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs [hunk 4]
```diff
@@ -57,29 +62,30 @@ public ApplicationContextManagerInMemory(AuthenticationStateProvider authenticat
 
     private async Task InitializeUser()
     {
-      Task<AuthenticationState> task = default;
-      try
+      var httpContext = HttpContext;
```
Comment (StefanOssendorf) [inline Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs:65]: why the variable? It can't change during life time of this objects instance.

File: Source/Csla.AspNetCore/Blazor/ApplicationContextManagerBlazor.cs (hunk 1 above)
Comment (rockfordlhotka) [reply Source/Csla.AspNetCore/Blazor/ApplicationContextManagerBlazor.cs:87]: I don't think it is our job to set the current principal. Blazor 8 appears to keep HttpContext.User and the AuthenticationStateProvider in sync all by itself.

I really think CSLA was overcomplicating some of this stuff earlier.

File: Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs (hunk 2 above)
Comment (rockfordlhotka) [reply Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs:55]: It is required by CSLA for other reasons, so yes, it is always registered or the app will fail on startup.

None of this code is run on the wasm client - this is all aspnetcore Blazor server stuff.
