### PR TITLE
 proposed fixes 

### LINKED ISSUE #2841: Fix for CreateInstanceDI which makes ServiceProvider parameter resolution work as expected
**EDIT:**
Whoops...fixed `if (parameters is null || parameters.Length > 0)` 
to be `if (parameters is null || parameters.Length == 0) `

@rockfordlhotka  Could I ask for a small tweak?  Depending on how you look at it, it's a bug or it's an enhancement...

In the current `ApplicationContext.CreateInstanceDI` method, when `CurrentServiceProvider` is NOT null, you call `ActivatorUtilities.CreateInstance(CurrentServiceProvider,...`  This works great when there are one or more manually passed in parameters. 

But it doesn't always work when `parameters.Length == 0` and the type/service being created has parameters that are registered with DI.   Microsoft's comment on their method is misleading making you think that DI will take care of resolution in that scenario but it does not.  It throws an error saying **"no suitable constructor found...bla bla"**.  
Now I know that is false because I put a breakpoint there and in the immediate window type `CurrentServiceProvider.GetRequiredService(objectType)` it works fine.  This means that the CreateInstance method is doing something different than the simple GetRequiredService call.

I've tested a very simple fix (IMO) that works.

**Currently it is like this:**
```cs
  if (CurrentServiceProvider != null)
    result = ActivatorUtilities.CreateInstance(CurrentServiceProvider, objectType, parameters);
  else
    result = Activator.CreateInstance(objectType, parameters);
...
```

**After adding one extra if condition:**
```cs
if (CurrentServiceProvider != null)
{
  if (parameters is null || parameters.Length == 0)
  {
    result = CurrentServiceProvider.GetRequiredService(objectType);
  }
  else
  {
    result = ActivatorUtilities.CreateInstance(CurrentServiceProvider, objectType, parameters);
  }
}
else
...
```

After this fix these three scenarios work:
1.  (works like it did before) When `CurrentServiceProvider` is null 
2.  (works like it did before) When `CurrentServiceProvider` is NOT null, and there are manually supplied parameters
3.  (now works)  When `CurrentServiceProvider` is NOT null, and there are NO supplied parameters, DI properly gets registered service and automatically resolves injected dependencies into that service type's constructor.

### PR DESCRIPTION
**Pull request by swegele**
#2841 and #2842

- New method `CreateInstanceViaServiceProvider` which uses **true** DI for object creation instead of CreateInstance. 

 [This answer](https://stackoverflow.com/a/45778712) from David Fowler finally helped me realize the difference between the current methods using CreateInstance versus ServiceProvider.GetRequiredService.  

The current methods create the object by CreateInstance without requiring DI registration.  During that operation the ServiceProvider (if present) merely attempts to resolve any missing parameters in its CTOR that were not manually passed in. 

Whereas, the new method actually uses DI for both _object creation AND for parameter resolution_.
I updated the comments on those existing methods to hopefully add clarity and distinctness.

- New interface `IContainsDeletedList` for the two objects which have a `DeletedList`

- Process `IContainsDeletedList` objects in LocalProxy for `SetApplicationContext`

### CODE REVIEW

File: Source/Csla/IContainsDeletedList.cs [hunk 1]
```diff
@@ -0,0 +1,20 @@
+﻿using System;
```
Comment (rockfordlhotka) [inline Source/Csla/IContainsDeletedList.cs:1]: This needs the header comment block like other files.

**Review by rockfordlhotka — CHANGES_REQUESTED** [review]

File: Source/Csla/IContainsDeletedList.cs (hunk 1 above)
Comment (swegele) [reply Source/Csla/IContainsDeletedList.cs]: I always struggle with wording/naming.  Hopefully that is clear.

**Comment by swegele** [comment]
Still learning how this all works.  I don't know if it's appropriate for me to:
- mark a conversation as resolved or should only you do that?
- re-request review after making change you requested...or is that overkill?

**Review by rockfordlhotka — APPROVED** [review]
